return {
  "catppuccin/nvim",
  name = "catppuccin",
  opts = {
    -- flavour = "auto",
    -- configuration options...
    integrations = {
      blink_cmp = true,
      indent_blankline = {
        enabled = true,
        scope_color = "lavender", -- catppuccin color (eg. `lavender`) Default: text
        colored_indent_levels = false,
      },
      noice = true,
      snacks = {
        enabled = true,
        indent_scope_color = "lavender", -- catppuccin color (eg. `lavender`) Default: text
      },
    },
    transparent_background = true,
    background = {
      dark = "mocha",
      light = "latte",
    },
    color_overrides = {
      mocha = {
        rosewater = "#ffb59d",
        -- flamingo = "#ffb59d",
        pink = "#fbb0d8",
        mauve = "#cdbdff",
        red = "#fbb0d8",
        maroon = "#fbb0d8",
        peach = "#ffb59d",
        yellow = "#f5bd6f",
        green = "#e9b9d3",
        teal = "#91d5ad",
        sky = "#c1c1ff",
        sapphire = "#b5c4ff",
        blue = "#c1c1ff",
        lavender = "#c1c1ff",
        text = "#e4e1e9",
        subtext1 = "#cccccc",
        subtext0 = "#bbbbbb",
        overlay2 = "#aaaaaa",
        overlay1 = "#999999",
        overlay0 = "#888888",
        surface2 = "#777777",
        surface1 = "#666666",
        surface0 = "#555555",
        -- surface0 = "#c6c4dd",
        base = "#131318",
        mantle = "#131318",
        crust = "#131318",
      },
      latte = {
        rosewater = "#ffb59d",
        flamingo = "#ffb59d",
        pink = "#fbb0d8",
        mauve = "#cdbdff",
        red = "#fbb0d8",
        maroon = "#fbb0d8",
        peach = "#ffb59d",
        yellow = "#f5bd6f",
        green = "#e9b9d3",
        teal = "#91d5ad",
        sky = "#c1c1ff",
        sapphire = "#b5c4ff",
        blue = "#c1c1ff",
        lavender = "#c1c1ff",
        text = "#e4e1e9",
        -- 明亮配色
        subtext1 = "#444444",
        subtext0 = "#555555",
        overlay2 = "#666666",
        overlay1 = "#777777",
        overlay0 = "#888888",
        surface2 = "#999999",
        surface1 = "#aaaaaa",
        surface0 = "#bbbbbb",
        base = "#131318",
        mantle = "#131318",
        crust = "#131318",
      },
    },
  },
}
